---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv
  namespace: elasticsearch
  labels:
    type: nfs
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: <ip>
    path: "/path/to/your/fileshare"
  mountOptions:
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pvc
  namespace: elasticsearch
  labels:
    type: nfs
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: ""
  volumeName: es-pv
  resources:
   requests:
     storage: 10Gi
  selector:
    matchLabels:
      type: nfs